server:
  port: 8080
  address: localhost
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  application:
    name: user-management-service
  profiles:
    default: dev
    active: dev
  liquibase:
    default-schema: public
    liquibase-schema: public
    change-log: db/changelog-master.xml
    enabled: false
    url: jdbc:postgresql://localhost:5432/user_db
    user: user
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        envers:
          audit_table_suffix: _AUD
          revision_field_name: rev
          revision_type_field_name: rev_type
          store_data_at_delete: true
          default_schema: user_audit
    generate-ddl: true
    hibernate:
      ddl-auto: update
  cloud:
    vault:
      uri: http://localhost:8200
      token: root
      kv:
        enabled: true
        backend: secret
        default-context: "kv/springboot-vault-docker"
  config:
    import: optional:vault://

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: false
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    metadata-map:
      zone: primary
    hostname: ${HOSTNAME:localhost}

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  auditevents:
    enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [traceId=%X{traceId},spanId=%X{spanId}]"
  level:
    com.immortals.authapp.security: DEBUG
    com.immortals.authapp.service: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema.internal.SchemaCreatorImpl: TRACE
    org.springframework: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui-auth-app.html
  api-docs:
    path: /api-docs
  show-actuator: true
  use-management-port: false

cache:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    command-timeout: 2s
    use-ssl: false
    pool-max-total: 16
    pool-max-idle: 16
    pool-min-idle: 4
    pool-max-wait: 1s
    auto-reconnect: true
    enabled: true

auth:
  jwt-issuer: https://your-issuer.example.com
  access-token-expiry-ms: 900000


  cache:
    static-resources:
      max-age-seconds: 31536000
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "https://yourdomain.com"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
      - "OPTIONS"
    allowed-headers:
      - "*"
    allow-credentials: true
    max-age: 31536000
  cookie:
    max-age: 604800
    secure : true


datasource:
  write:
    url: jdbc:postgresql://localhost:5432/user_db
    username: user
    password: admin
    driver-class-name: org.postgresql.Driver
  read:
    url: jdbc:postgresql://localhost:5432/user_db
    username: replicator
    password: test
    driver-class-name: org.postgresql.Driver

